### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by KyuubiRan**
重写

### CODE REVIEW

**Comment by qwq233** [comment]
Can one of the admins verify this patch?

**Comment by KyuubiRan** [comment]
> Can one of the admins verify this patch?

我自己

**Comment by keta1** [comment]
让我拉下来看看

**Review by keta1 — DISMISSED** [review]

**Review by keta1 — APPROVED** [review]

**Comment by qwq233** [comment]
> > Can one of the admins verify this patch?
> 
> 我自己

这是jenkins自动发的(((((

**Pull request merged**
