### PR TITLE
Move ProcessInfo into util

### PR DESCRIPTION
**Pull request by KyuubiRan**

### CODE REVIEW

**Comment by qwq233** [comment]
Can one of the admins verify this patch?

**Review by keta1 — APPROVED** [review]

**Comment by KyuubiRan** [comment]
> Can one of the admins verify this patch?

myself

**Review by NextAlone — APPROVED** [review]

**Comment by NextAlone** [comment]
> Can one of the admins verify this patch?

himself

**Comment by keta1** [comment]
> > Can one of the admins verify this patch?
> 
> myself

为啥要回复机器人

**Comment by KyuubiRan** [comment]
> > > Can one of the admins verify this patch?
> > 
> > 
> > myself
> 
> 为啥要回复机器人

好玩 下次还玩

**Pull request merged**
